[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/mavlink/c_library_v2.git
build_flags =
    -DMAVLINK_DIALECT=ardupilotmega
